sudo: false
language: cpp

branches:
  only:
  - master

env:
  global:
    - BIN=play

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: require
      addons:
        apt:
          sources:
            # Add ppa for gcc-7
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            # Set ppa to get a modern version of qt
            - sourceline: 'ppa:beineri/opt-qt-5.12.1-xenial'
          packages:
            - g++-7
            - git
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

install:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    export QTV=qt512;
    sudo apt update -qq;
    echo "Install qt libraries";
    sudo apt install build-essential ${QTV}base
    ${QTV}quickcontrols ${QTV}quickcontrols2
    ${QTV}graphicaleffects ${QTV}svg ${QTV}scxml libgl1-mesa-dev;
    export ARTIFACT="$BIN*.AppImage";
  fi

script:
- eval "${MATRIX_EVAL}"
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    echo "Load qt env";
    source /opt/qt*/bin/qt*-env.sh;
    echo "Build project";
    mkdir build && cd build;
    qmake ..;
    make;
    echo "Create deploy folder";
    mkdir deploy;
    cp ../deploy/icon.png deploy/;
    cp ../deploy/$BIN.desktop deploy/;
    mv $BIN deploy/;
    echo "Donwload and run linuxdeployqt";
    wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
    chmod a+x linuxdeployqt*.AppImage;
    unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH;
    ./linuxdeployqt*.AppImage deploy/$BIN.desktop -unsupported-allow-new-glibc -bundle-non-qt-libs -extra-plugins=iconengines,imageformats -verbose=2 -qmldir=../qml -appimage;
    mv $BIN*.AppImage $BIN.AppImage;
  fi

after_success:
- curl --upload-file $ARTIFACT https://transfer.sh/$BIN.AppImage
